#+STYLE: <style type="text/css"> #text-5-1 b { color: red } </style>


# [[https://travis-ci.org/CodyReichert/whatcd-cli.svg?branch=master]]

whatcd-cli - A Command Line Interface for What.CD 

# [![Build Status](https://travis-ci.org/CodyReichert/whatcd-cli.svg?branch=master)](https://travis-ci.org/CodyReichert/whatcd-cli)
whatcd-cli is a command line interface for browsing, searching, and downloading from what.cd.

* Install
** NPM install
   The quickest way to install is to get the latest version from npm:
   
   #+BEGIN_SRC bash
       $ npm install -g whatcd-cli
   #+END_SRC  

** Latest from Github
   or get the latest changes from github

   #+BEGIN_SRC bash
       $ npm install -g CodyReichert/whatcd-cli
   #+END_SRC

** Running
   And that's it! You can run it with:

   #+BEGIN_SRC bash
         $ whatcd
   #+END_SRC

Read the alternative install section below for more help with installing.

*You'll need to create a config file with your username a password. Read more below.*

* Configuration
  Store your what.cd credentials in a .whatcd config file in the top
  level of your home directory (`~/.whatcd` or `/home/<username>/.whatcd`).

** Config file
  #+BEGIN_SRC javascript
      module.exports =  {
        username: "Your what.cd username",
        password: "Your what.cd password",
        torrentDirectory: "/path/to/save/torrents/"
      }
  #+END_SRC

  The torrentDirectory is where whatcd-cli will save all torrent files. My recommendation
  is to have your torrent client automatically start files added to this directory.

** Running without a config file
   whatcd-clie does not require you to keep a plain text configuration. If you start whatcd-cli
   without a config file, it will simply prompt you for your username and password.
   If you download a file in this mode, it will always download to the current working directory.


* Usage
  This command line interface allows you to browse what.cd torrents, arists,
  and albums (and a couple other things) directly from the command line.
  Currently, most of the searches you can make on what.cd are supported.
  
  To search, you can enter a query from the main menu (which will match all
  albums, artists, singles, etc), or you can choose one of the advanced search options:


    - *(D)* Download: Enter "D" or "d", from the main menu to download a torrent file.
          You will be prompted for the ID. It will save to your torrentsDirectory set in your settings.js file.
    - *(Top)* Top 10: Enter "Top" or "top" from the main menu to view the top 10 most
         active torrents of the day.
    - *(S)* Similar: Enter "S" or "s" from the main menu to find similar artists.
         You will be prompted for an artist name. It will show the first 10 (or less) matches.
    - *(A)* Artist search: Not yet implemented.
    - *(T)* Torrent search: Not yet implemented.

  For more help, licensing information, or to submit issues
  view the README at http://github.com/CodyReichert/whatcd-cli

* Roadmap and Future Development
  Below is a list of features and changes that I would personally like to see happen.
  Feel free to create an issue with a feature request to get it added to the roadmap.
  Or even better, create a pull request implementing the feature you want.

** Command line API (non-interactive mode)
   One of the first things I want to do is have single command
   interactions, so the interactive mode is optional. So you could just
   do something like this to download a file:

   #+BEGIN_SRC bash
         $ whatcd -d "torrent-id"
   #+END_SRC

   or this to get album an album in a certain format

   #+BEGIN_SRC bash
       $ whatcd -a "Brand New" -b "Daisy" -f "FLAC"
   #+END_SRC

* Alternative installations

** Installing without NPM 
   If you don't have or want to use npm, you can clone the repo and run directly with node:

   #+BEGIN_SRC bash
       git clone git@github.com:CodyReichert/whatcd-cli
       cd whatcd-cli/
       npm install
       node src/whatcd.js
   #+END_SRC

   *Follow the config files steps above*

** Latest stable release from github
   The npm install command above will install the latest changes. If you have problems
   install the lastest stable release instead.

   #+BEGIN_SRC bash
       npm install -g CodyReichert/whatcd-cli/0.1.0
   #+END_SRC

* Licensing and Disclaimer

** GNU General Public License v3.0

   *This software is licensed under the GNU General Publice License Version 3.0*
   
   WhatCD-cli is a command-line interface for browsing and downloading what.cd torrents.
   
   Copyright (C) 2014 Cody Reichert
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see
   [[http://www.gnu.org/licenses/]]
   
   For any additional information or questions, you can contact me
   at: [[mailto:codyreichert@gmail.com][codyreichert@gmail.com]]
